// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYMLWLAbbCCgN9F19MxfGpb1YfSPyY6Pc',
    appId: '1:91468661410:web:79f4fb1063d0911aea4dfb',
    messagingSenderId: '91468661410',
    projectId: 'upwork-task-8f47c',
    authDomain: 'upwork-task-8f47c.firebaseapp.com',
    storageBucket: 'upwork-task-8f47c.firebasestorage.app',
    measurementId: 'G-JTZLJ9B62W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtGxqFpTNAXVcnVJtW8qcs_svWQnG6J_0',
    appId: '1:91468661410:android:81f2131fafe91b60ea4dfb',
    messagingSenderId: '91468661410',
    projectId: 'upwork-task-8f47c',
    storageBucket: 'upwork-task-8f47c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwUtgXVnvQdokGQmB41j_H3jPR6MBa0g',
    appId: '1:91468661410:ios:0182274ea0cb5384ea4dfb',
    messagingSenderId: '91468661410',
    projectId: 'upwork-task-8f47c',
    storageBucket: 'upwork-task-8f47c.firebasestorage.app',
    androidClientId: '91468661410-lo5g4lbsm1ljvq095aqscmlesd56qkq0.apps.googleusercontent.com',
    iosClientId: '91468661410-0blalav47b8rdiqoh7h6s1aibv9sq3q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.carWashApp',
  );
}
